# Lab | Web Scraping Single Page (GNOD part 1)

### PART 1

In [18]:
# 1. import libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re
import random
from pandas.io.json import json_normalize
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.metrics import silhouette_score
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA    
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.cluster import KMeans
import numpy as np

from random import randint
from time import sleep

In [2]:
#2. attribute url
url = "https://www.popvortex.com/music/charts/top-100-songs.php"

In [3]:
# 3. download html with a get request
response = requests.get(url)
response.status_code # 200 status code means OK!

200

In [6]:
# 4. parse html (create the 'soup')
soup = BeautifulSoup(response.content, "html.parser")
#soup

In [7]:
#divide the different criteria into a different lists to be put into our final dataframe

artist = []
song = []
genre = []
year = []

num_iter = len("body > div.container > div:nth-child(4) > div.col-xs-12.col-md-8 > div.chart-wrapper > div.feed-item")

songart = soup.select("body > div.container > div:nth-child(4) > div.col-xs-12.col-md-8 > div.chart-wrapper > div.feed-item")
genlist = soup.select("body > div.container > div:nth-child(4) > div.col-xs-12.col-md-8 > div.chart-wrapper > div.feed-item > div.chart-content")
yearlist = soup.select("body > div.container > div:nth-child(4) > div.col-xs-12.col-md-8 > div.chart-wrapper > div.feed-item > div.chart-content > ul > li:nth-child(2)")

for i in range(num_iter):
    artist.append(songart[i].em.get_text())
    song.append(songart[i].cite.get_text())
    year.append(yearlist[i].get_text())    
    try:
        genre.append(genlist[i].ul.li.a.get_text())
    except:
        genre.append('Unknown')

In [10]:
#Attribute the lists to a dataframe

top100 = pd.DataFrame({'artist':artist
                    ,'track':song
                    ,'genre':genre
                    ,'year':year})

In [11]:
top100

,artist,track,genre,year
0,Jimmy Buffett,Margaritaville,Pop,"Release Date: January 1, 1977"
1,Jimmy Buffett,Come Monday,Pop,"Release Date: January 1, 1974"
2,Oliver Anthony Music,Rich Men North of Richmond,Country,"Release Date: August 11, 2023"
3,Jimmy Buffett,Cheeseburger In Paradise,Pop,"Release Date: January 1, 1985"
4,Jimmy Buffett,"Changes In Latitudes, Changes In Attitudes",Pop,"Release Date: January 1, 1977"
...,...,...,...,...
95,Vy Napi,"Don't Keep It In Your Heart, There's Nothing H...",Unknown,"Release Date: July 3, 2023"
96,Evanescence,Bring Me to Life,Rock,"Release Date: February 4, 2003"
97,Doja Cat,Demons,New Release,Genre: Rap
98,Creedence Clearwater Revival,Bad Moon Rising,Rock,"Release Date: July 1, 1968"
99,Smash Mouth,All Star,Alternative,"Release Date: May 4, 1999"

In [12]:
#In the year column we have a Genre: leak. We will split these genres 

def genresplit(value):
    if 'Genre:' in value:
        name = value.split('Genre: ')[1]
        
        return name
    else:
        return value

In [13]:
#and move these genres 
top100['genre'] = top100['genre'].apply(genresplit)
top100['year'] = top100['year'].apply(genresplit)

In [14]:
def tidy(value):

    type1 = value['genre']
    type2 = value['year']
    if str(type1) == 'New Release':
        return type2
    else:
        return type1

    
top100['genre'] = top100.apply(tidy,axis=1)

In [15]:
#Now we are going to split the year column by the comma and find the year value. "Nan" values filled with 2023, because it was originally a "New Release" value
top100['year'] = top100['year'].str.split(", ", n = 1, expand = True)[1]
top100['year'] = top100['year'].fillna(2023)
top100['track'] = top100['track'].str.strip()

In [16]:
top100

,artist,track,genre,year
0,Jimmy Buffett,Margaritaville,Pop,1977
1,Jimmy Buffett,Come Monday,Pop,1974
2,Oliver Anthony Music,Rich Men North of Richmond,Country,2023
3,Jimmy Buffett,Cheeseburger In Paradise,Pop,1985
4,Jimmy Buffett,"Changes In Latitudes, Changes In Attitudes",Pop,1977
...,...,...,...,...
95,Vy Napi,"Don't Keep It In Your Heart, There's Nothing H...",Unknown,2023
96,Evanescence,Bring Me to Life,Rock,2003
97,Doja Cat,Demons,Rap,2023
98,Creedence Clearwater Revival,Bad Moon Rising,Rock,1968
99,Smash Mouth,All Star,Alternative,1999

### PART 2